//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadParcial2Ajavp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string director { get; set; }
        public int episodios { get; set; }
        public System.DateTime fechaEstreno { get; set; }
        public short estado { get; set; }
    }
}
